DROP TABLE IF EXISTS "FACT_Job_Skill" CASCADE;
DROP TABLE IF EXISTS "FACT_Job_Location" CASCADE;
DROP TABLE IF EXISTS "FACT_Company_Industry" CASCADE;
DROP TABLE IF EXISTS "FACT_Job_Posting" CASCADE;
DROP TABLE IF EXISTS "DIM_Company" CASCADE;
DROP TABLE IF EXISTS "DIM_Job_Title" CASCADE;
DROP TABLE IF EXISTS "DIM_Job_Type" CASCADE;
DROP TABLE IF EXISTS "DIM_Experience_Level" CASCADE;
DROP TABLE IF EXISTS "DIM_Location" CASCADE;
DROP TABLE IF EXISTS "DIM_Industry" CASCADE;
DROP TABLE IF EXISTS "DIM_Skill" CASCADE;
DROP TABLE IF EXISTS "DIM_Date_Posted" CASCADE;

CREATE TABLE "DIM_Skill" (
    skill_id        SERIAL PRIMARY KEY,
    skill_name      VARCHAR(255) NOT NULL,
    skill_group     VARCHAR(255),
    skill_type      VARCHAR(50),
    skill_category  VARCHAR(255)
);


CREATE TABLE "FACT_Job_Posting" (
  "job_posting_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" int,
  "date_posted" date,
  "job_title_id" int,
  "job_type_id" int,
  "experience_level_id" int,
  "salary_min" int,
  "salary_max" int,
  "salary_text" varchar
);


CREATE TABLE "DIM_Company" (
  "company_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" varchar
);

CREATE TABLE "DIM_Job_Title" (
  "job_title_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_title" varchar
);

CREATE TABLE "DIM_Job_Type" (
  "job_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_type" varchar
);

CREATE TABLE "DIM_Experience_Level" (
  "experience_level_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "experience_level" varchar
);

CREATE TABLE "DIM_Date_Posted" (
  "date" date PRIMARY KEY,
  "dateint" int,
  "dayinweek" int,
  "dayofmonth" int,
  "dayofweekname" varchar,
  "finmonth" int,
  "finquarter" varchar,
  "finquarternumber" int,
  "finyear" int
);

CREATE TABLE "DIM_Location" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" varchar,
  "city" varchar,
  "region" varchar
);

CREATE TABLE "DIM_Industry" (
  "industry_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "industry_name" varchar
);


CREATE TABLE "FACT_Job_Skill" (
  "job_posting_id" bigint,
  "skill_id" int,
  PRIMARY KEY ("job_posting_id", "skill_id")
);

CREATE TABLE "FACT_Job_Location" (
  "job_posting_id" bigint,
  "location_id" int,
  PRIMARY KEY ("job_posting_id", "location_id")
);

CREATE TABLE "FACT_Company_Industry" (
  "company_id" int,
  "industry_id" int,
  PRIMARY KEY ("company_id", "industry_id")
);

ALTER TABLE "FACT_Job_Skill" ADD FOREIGN KEY ("job_posting_id") REFERENCES "FACT_Job_Posting" ("job_posting_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Skill" ADD FOREIGN KEY ("skill_id") REFERENCES "DIM_Skill" ("skill_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Location" ADD FOREIGN KEY ("job_posting_id") REFERENCES "FACT_Job_Posting" ("job_posting_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Location" ADD FOREIGN KEY ("location_id") REFERENCES "DIM_Location" ("location_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Company_Industry" ADD FOREIGN KEY ("company_id") REFERENCES "DIM_Company" ("company_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Company_Industry" ADD FOREIGN KEY ("industry_id") REFERENCES "DIM_Industry" ("industry_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("company_id") REFERENCES "DIM_Company" ("company_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("job_title_id") REFERENCES "DIM_Job_Title" ("job_title_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("job_type_id") REFERENCES "DIM_Job_Type" ("job_type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("date_posted") REFERENCES "DIM_Date_Posted" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("experience_level_id") REFERENCES "DIM_Experience_Level" ("experience_level_id") DEFERRABLE INITIALLY IMMEDIATE;
