
CREATE TABLE "FACT_Job_Posting" (
  "job_posting_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" int,
  "date_posted" date,
  "job_title_id" int,
  "job_type_id" int,
  "experience_level_id" int,
  "salary_min" int,
  "salary_max" int,
  "salary_text" varchar
);


CREATE TABLE "DIM_Company" (
  "company_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" varchar
);

CREATE TABLE "DIM_Job_Title" (
  "job_title_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_title" varchar
);

CREATE TABLE "DIM_Job_Type" (
  "job_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_type" varchar
);

CREATE TABLE "DIM_Experience_Level" (
  "experience_level_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "experience_level" varchar
);

CREATE TABLE "DIM_Date_Posted" (
  "date" date PRIMARY KEY,
  "dateint" int,
  "dayinweek" int,
  "dayofmonth" int,
  "dayofweekname" varchar,
  "finmonth" int,
  "finquarter" varchar,
  "finquarternumber" int,
  "finyear" int
);

CREATE TABLE "DIM_Location" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" varchar,
  "city" varchar,
  "region" varchar
);

CREATE TABLE "DIM_Industry" (
  "industry_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "industry_name" varchar
);

CREATE TABLE "DIM_Skill" (
  "skill_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "skill_name" varchar,
  "skill_type" varchar
);
ALTER TABLE "DIM_Skill" 
ADD COLUMN skill_category VARCHAR(255);

CREATE TABLE "FACT_Job_Skill" (
  "job_posting_id" bigint,
  "skill_id" int,
  PRIMARY KEY ("job_posting_id", "skill_id")
);

CREATE TABLE "FACT_Job_Location" (
  "job_posting_id" bigint,
  "location_id" int,
  PRIMARY KEY ("job_posting_id", "location_id")
);

CREATE TABLE "FACT_Company_Industry" (
  "company_id" int,
  "industry_id" int,
  PRIMARY KEY ("company_id", "industry_id")
);

ALTER TABLE "FACT_Job_Skill" ADD FOREIGN KEY ("job_posting_id") REFERENCES "FACT_Job_Posting" ("job_posting_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Skill" ADD FOREIGN KEY ("skill_id") REFERENCES "DIM_Skill" ("skill_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Location" ADD FOREIGN KEY ("job_posting_id") REFERENCES "FACT_Job_Posting" ("job_posting_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Location" ADD FOREIGN KEY ("location_id") REFERENCES "DIM_Location" ("location_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Company_Industry" ADD FOREIGN KEY ("company_id") REFERENCES "DIM_Company" ("company_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Company_Industry" ADD FOREIGN KEY ("industry_id") REFERENCES "DIM_Industry" ("industry_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("company_id") REFERENCES "DIM_Company" ("company_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("job_title_id") REFERENCES "DIM_Job_Title" ("job_title_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("job_type_id") REFERENCES "DIM_Job_Type" ("job_type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("date_posted") REFERENCES "DIM_Date_Posted" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FACT_Job_Posting" ADD FOREIGN KEY ("experience_level_id") REFERENCES "DIM_Experience_Level" ("experience_level_id") DEFERRABLE INITIALLY IMMEDIATE;

-- Tests
-- Test 1
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public';



select * from "DIM_Skill" ds 

select * from "FACT_Job_Skill" fjs 

select * from "FACT_Job_Posting" fjp 

select * from "FACT_Job_Location" fjl 

select * from "DIM_Location" dl 

select * from "DIM_Date_Posted" ddp 

select * from "DIM_Job_Title" djt 

select * from "DIM_Company" dc 

select * from "FACT_Company_Industry" fci 

select * from "DIM_Industry" di 

select * from "DIM_Experience_Level" del 

select * from "DIM_Job_Type" djt 

-- Test 2
SELECT 'DIM_Company' as table_name, COUNT(*) FROM "DIM_Company"
UNION ALL SELECT 'DIM_Job_Title', COUNT(*) FROM "DIM_Job_Title"
UNION ALL SELECT 'DIM_Skill', COUNT(*) FROM "DIM_Skill"
UNION ALL SELECT 'DIM_Location', COUNT(*) FROM "DIM_Location"
UNION ALL SELECT 'DIM_Industry', COUNT(*) FROM "DIM_Industry"
UNION ALL SELECT 'DIM_Experience_Level', COUNT(*) FROM "DIM_Experience_Level"
UNION ALL SELECT 'DIM_Date_Posted', COUNT(*) FROM "DIM_Date_Posted"
UNION ALL SELECT 'FACT_Job_Posting', COUNT(*) FROM "FACT_Job_Posting"
UNION ALL SELECT 'FACT_Job_Skill', COUNT(*) FROM "FACT_Job_Skill"
UNION ALL SELECT 'FACT_Job_Location', COUNT(*) FROM "FACT_Job_Location"
UNION ALL SELECT 'FACT_Company_Industry', COUNT(*) FROM "FACT_Company_Industry";

-- Test 3
SELECT 
    f.job_posting_id,
    c.company_name,
    t.job_title,
    e.experience_level,
    f.salary_min,
    f.salary_max,
    l.city,
    f.date_posted
FROM "FACT_Job_Posting" f
JOIN "DIM_Company" c ON f.company_id = c.company_id
JOIN "DIM_Job_Title" t ON f.job_title_id = t.job_title_id
JOIN "DIM_Experience_Level" e ON f.experience_level_id = e.experience_level_id
JOIN "FACT_Job_Location" fl ON f.job_posting_id = fl.job_posting_id
JOIN "DIM_Location" l ON fl.location_id = l.location_id
LIMIT 10;


-- Test 4
SELECT 
    s.skill_name,
    s.skill_category,
    s.skill_type,
    COUNT(*) as demand_count
FROM "FACT_Job_Skill" fs
JOIN "DIM_Skill" s ON fs.skill_id = s.skill_id
GROUP BY s.skill_name, s.skill_category, s.skill_type
ORDER BY demand_count DESC
LIMIT 10;

-- Test 5
SELECT 
    e.experience_level,
    ROUND(AVG(f.salary_min)) as avg_salary_min,
    ROUND(AVG(f.salary_max)) as avg_salary_max
FROM "FACT_Job_Posting" f
JOIN "DIM_Experience_Level" e ON f.experience_level_id = e.experience_level_id
GROUP BY e.experience_level
ORDER BY avg_salary_min;

-- Test 6
SELECT 
    f.job_posting_id,
    t.job_title,
    s.skill_name
FROM "FACT_Job_Skill" fs
JOIN "FACT_Job_Posting" f ON fs.job_posting_id = f.job_posting_id
JOIN "DIM_Job_Title" t ON f.job_title_id = t.job_title_id
JOIN "DIM_Skill" s ON fs.skill_id = s.skill_id
LIMIT 15;


select * from "FACT_Job_Posting" fjp 

-- 83 Companies 
select * from "DIM_Company" dc 

-- Entire Dataset
SELECT 
    f.job_posting_id,
    c.company_name,
    t.job_title
FROM "FACT_Job_Posting" f
JOIN "DIM_Company" c ON f.company_id = c.company_id
JOIN "DIM_Job_Title" t ON f.job_title_id = t.job_title_id
ORDER BY f.job_posting_id;

-- Test for Duplicate Companies
SELECT 
    c.company_name,
    COUNT(*) as jobs_posted
FROM "FACT_Job_Posting" f
JOIN "DIM_Company" c ON f.company_id = c.company_id
GROUP BY c.company_name
HAVING COUNT(*) > 1
ORDER BY jobs_posted DESC;

-- Data Insights' Number of Postings
SELECT f.job_posting_id, c.company_name 
FROM "FACT_Job_Posting" f
JOIN "DIM_Company" c ON f.company_id = c.company_id
WHERE c.company_name = 'Data Insights';

-- Most Active Recruiters
SELECT 
    c.company_name,
    COUNT(*) as jobs_posted
FROM "FACT_Job_Posting" f
JOIN "DIM_Company" c ON f.company_id = c.company_id
GROUP BY c.company_name
ORDER BY jobs_posted DESC;